### ISSUE TITLE
Crashes in Renderer process in Electron

### ISSUE THREAD

**Issue by robogeek** [jy95/path-directories#2]
The application I'm writing is on Electron - and I want to use this module from the Renderer process.  However, I'm getting this error:

```
Cannot read property 'normalize' of undefined"
```

After some time I narrowed this down to the `path-directories` module.  The module does call the `normalize` function.

In the Electron Renderer process the `path` module looks like this:

```
{ resolve: [Function],
  normalize: [Function],
  isAbsolute: [Function],
  join: [Function],
  relative: [Function],
  sep: '/',
  delimiter: ':',
  dirname: [Function],
  basename: [Function],
  extname: [Function] }
```

As you'll notice it does not have `win32` or `posix` fields.  The `path-directories` module requires those fields in order to function.

In Electron the Renderer process is equal to a Browser window, and the JavaScript in that case is browser JavaScript.  Except that it also acts like Node.js.  But apparently there are a couple differences, such as the path module being different.  

Hurm, according to the Architecture page the programmer has full access to Node.js modules https://electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes

Not sure what to make of that claim, since obviously the `path` module object is different as is the `process` module object.

I'm not sure what this module can do about this issue.  

One possibility is if this is `null`

```
let pathModule = (isWindowsPath) ? require("path").win32 : require("path").posix;
```

Then to substitute the value of `require('path')`.  BUT .. this would negate the ability to parse a Windows path on Linux/Mac and vice versa.

**Comment by jy95** [comment]
Hmm  ... 

Here is the official implementation of the path module : https://github.com/nodejs/node/blob/28e4e43e513ae90e8a4236dbae7f3442ab8dbb4f/lib/path.js#L1531

As you can see, the `win32` and `posix` fields should exist , even in the browser ...

Do you have tried the two way they show in "Using Electron APIs" ? 

Two possibility to handle this : 
- Send a issue to Electron (this behaviour is undocumented ^^)
- Use your own version of the both implementations of path (like [path-posix](https://www.npmjs.com/package/path-posix) and [path-win32](https://www.npmjs.com/package/path-win32) ) . What I can do is allow you to inject yours like this (of course this will be a optional parameter)

```js
const dirnames = require('path-directories');
// Windows path - gives [ 'D:', 'DDL', 'ANIME', 'les chevaliers du zodiaques' ]
// 
dirnames("D:\\DDL\\ANIME\\les chevaliers du zodiaques\\whateverFile.avi", 
{win32: require("yourOwnImplement"), posix: ...} );
```

**Comment by robogeek** [comment]
After some thinking about this ... First, my custom component works fine if I directly include it in the demo application.  The problem arose when I moved its code to its own repository and used a different build process.  That build process uses Webpack, and I simply do not know Webpack (yet).  

The custom component build process is clearly what's giving it a limited version of the `path` module.  I don't think it's Electron that did - because while running an Electron app I can inspect the `path` module and see that it's the full thing.

In my custom component I implemented a module that performs similar function to `path-directories` but includes workarounds for the limited environment.

See: https://github.com/robogeek/vue-file-tree/blob/master/src/path-splitdirs.js

The `path-normalize` module supplies the `path.normalize` function if it's missing, and the `parse-filepath` module supplies `path.parse` if it's missing.  You might find this module to be interesting.

**Comment by jy95** [comment]
Don't worry about your not knowledge about Webpack : most of the time, developpers uses configuration presets ( they are so many trival cases that causes errors with this builder )

You could try this : [Integrate Native Node.js Modules Into an Electron App ](http://blog.cinan.sk/2018/02/22/integrate-native-node-dot-js-modules-into-an-electron-app-1-slash-2/)

In short, either : 
- `target: 'electron-renderer'` [docs](https://webpack.js.org/configuration/target/#string)

> Compile for Electron for renderer process, providing a target using JsonpTemplatePlugin, FunctionModulePlugin for browser environments and NodeTargetPlugin and ExternalsPlugin for CommonJS and Electron built-in modules.

- `externals: { bindings: 'require("bindings")' }` [docs](https://www.npmjs.com/package/bindings) and [other docs](https://webpack.js.org/configuration/externals/)

> Helper module for loading your native module's .node file
This is a helper module for authors of Node.js native addon modules. It is basically the "swiss army knife" of require()ing your native module's .node file.

> Throughout the course of Node's native addon history, addons have ended up being compiled in a variety of different places, depending on which build tool and which version of node was used. To make matters worse, now the gyp build tool can produce either a Release or Debug build, each being built into different locations.

**Comment by jonschlinkert** [comment]
Or you could just do:

```js
const split = filepath => {
  const parts = filepath.split(/[\\/]/);
  const result = parts.length > 1 ? parts.slice(0, -1) : parts;
  if (result[0] === '') result[0] = '/';
  return result;
};
```

This should pass all tests and doesn't require `path`.

**Comment by jy95** [comment]
thanks @jonschlinkert : PR is welcome 👍

**Comment by jy95** [comment]
Thanks @jonschlinkert : I just released a version that should be plateform independant.
